"""Atualização Schemas

Revision ID: 57bfae4d2c30
Revises: 14552e5367f4
Create Date: 2026-09-17 22:27:32.481584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bfae4d2c30'
down_revision: Union[str, Sequence[str], None] = '14552e5367f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.alter_column('arma',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.alter_column('arma',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
