"""Adiciona tabela atributos

Revision ID: e62f7cfd95f3
Revises: 57bfae4d2c30
Create Date: 2026-09-20 13:45:29.927810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62f7cfd95f3'
down_revision: Union[str, Sequence[str], None] = '57bfae4d2c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributos',
    sa.Column('id_personagem', sa.Integer(), nullable=False),
    sa.Column('Vida', sa.Integer(), nullable=True),
    sa.Column('Escudo', sa.Integer(), nullable=False),
    sa.Column('Vigor', sa.Integer(), nullable=True),
    sa.Column('Sorte', sa.Integer(), nullable=True),
    sa.Column('Inteligencia', sa.Integer(), nullable=True),
    sa.Column('Forca', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personagem'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id_personagem')
    )
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Atributos_Totais', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_column('Atributos_Totais')

    op.drop_table('atributos')
    # ### end Alembic commands ###
